name: profile_app
description: A Flutter profile application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  qr_flutter: ^4.1.0
  window_manager: ^0.3.7
  supabase_flutter: ^2.8.0
  flutter_dotenv: ^5.2.0
  image_picker: ^1.2.1
  mobile_scanner: ^3.5.2
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  image_gallery_saver: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
